theme = "minimal-dark"
[keys.insert]
"C-h" = "move_char_left"
"C-j" = "move_line_down"
"C-k" = "move_line_up"
"C-l" = "move_char_right"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
